# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
        REACT_APP_CloudKit_environment: production
        REACT_APP_CloudKit_apiToken: ${{ secrets.CK_API_TOKEN }}
        REACT_APP_GoogleMap_key: ${{ secrets.GM_API_TOKEN }}

    - name: Automated Version Bump
      if: github.ref == 'refs/heads/master'
      uses: phips28/gh-action-bump-version@v8.0.18

    - name: 🎉 Deploy
      if: github.ref == 'refs/heads/master'
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: "build/"
        server-dir: ${{ secrets.TARGET_PATH }}
